.TH _PRINTF 1 "11 July 2022"

.SH NAME

_printf /- format and print name

.SH SYNOPSIS

/fB_printf/fP /fUFORMAT/fP [/fUARGUMENT/fP]

.SH DESCRIPTION

/fB_printf/fP Print ARGUMENT(s) according to FORMAT.

.SH AUTHOR

Written by Franco Van den Berg and Thomas Beyene.

.SH BUGS

Incomplete as it does not include all features of printf. 
